### PR TITLE
Feature/front-create account

### PR DESCRIPTION
**Pull request by SeoYoujune**
I have completed a Account Creation page that takes input for name, email, student ID, and password.

### CODE REVIEW

**Review by Hyunmin0502 — COMMENTED** [review]
Nice work

**Review by Hyunmin0502 — APPROVED** [review]

**Review by Hyunmin0502 — APPROVED** [review]

**Review by Hyunmin0502 — DISMISSED** [review]

**Review by mmuhunn — DISMISSED** [review]
The addition of the login account creation page has been appropriately integrated into the existing files.👍👍

**Review by hellinii — APPROVED** [review]
good job yoojun

**Review by mmuhunn — APPROVED** [review]
Why it doen't be merged.

**Review by BaikSeung — APPROVED** [review]

**Pull request closed without merging**
